name: AWS Cost by Tags

on:
  schedule:
    - cron: '40 8 * * *'  

jobs:
  get-aws-costs:
    runs-on: ubuntu-latest

    steps:
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli jq curl

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Format and send cost data to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          START_DATE=$(date '+%Y-%m-01')
          END_DATE=$(date '+%Y-%m-%d')

          if [ "$TODAY" = "$END_DATE" ]; then
            echo "Today is the end date. Script will not run."
          exit 0
          fi
          
          COST_DATA=$(aws ce get-cost-and-usage \
            --time-period Start=${START_DATE},End=${END_DATE} \
            --granularity MONTHLY \
            --metrics "BlendedCost" \
            --group-by Type=TAG,Key="Client" \
            --query 'ResultsByTime[0].Groups' \
            --output json)

          LIST_ITEMS=$(echo $COST_DATA | jq -r '
            .[] | 
            .Keys[0] as $tag | 
            .Metrics.BlendedCost.Amount as $cost | 
            {"type": "rich_text_section", "elements": [{"type": "text", "text": "\($tag): \($cost)"}]}
          ' | jq -s .)
          
          PAYLOAD=$(jq -n --argjson list_items "$LIST_ITEMS" '
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "AWS current monthly costs 💰",
                    "emoji": true
                  }
                },
                {
                  "type": "rich_text",
                  "elements": [
                    {
                      "type": "rich_text_list",
                      "style": "bullet",
                      "elements": $list_items
                    }
                  ]
                }
              ]
            }
          ')
          echo "$PAYLOAD"
          curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $SLACK_WEBHOOK_URL
