name: Extract Github Data On Demand

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: Retrieve PR and PR comment informations from a certain date. Format is 'day/month/year hour:minute:second'
        required: true
        default: 10/01/23 00:00:00
        type: string
      end_date:
        description: Retrieve PR and PR comment informations to a certain date. Format is 'day/month/year hour:minute:second'
        required: true
        default: 09/30/24 23:59:59
        type: string

jobs:
  extract-github-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          cache: "pip"
      - run: pip install -r requirements.txt

      - name: Generate CSVs
        run: |
          python extract_github_data.py \
            --github_token '${{ secrets.READ_GITHUB_PR_TOKEN }}' \
            --start_date '${{ inputs.start_date }}' \
            --end_date '${{ inputs.end_date }}'

      - name: Upload PR Data CSV
        uses: actions/upload-artifact@v4
        with:
          name: pr_output.csv
          path: output/pr_output.csv
          if-no-files-found: error

      - name: Upload PR Comment Data CSV
        uses: actions/upload-artifact@v4
        with:
          name: pr_comment_output.csv
          path: output/pr_comment_output.csv
          if-no-files-found: error
